// Auto-generated from /mnt/data/2ways.glb.
// This file is intentionally data-only so it can be used by Three.js, React Three Fiber,
// Babylon.js adapters, editor tooling, or custom animation systems.

export const AVATAR_BONE_NAMES = [
  "root",
  "pelvis",
  "spine_01",
  "spine_02",
  "spine_03",
  "neck_01",
  "head",
  "head_leaf",
  "clavicle_l",
  "upperarm_l",
  "lowerarm_l",
  "hand_l",
  "index_01_l",
  "index_02_l",
  "index_03_l",
  "index_04_leaf_l",
  "middle_01_l",
  "middle_02_l",
  "middle_03_l",
  "middle_04_leaf_l",
  "pinky_01_l",
  "pinky_02_l",
  "pinky_03_l",
  "pinky_04_leaf_l",
  "ring_01_l",
  "ring_02_l",
  "ring_03_l",
  "ring_04_leaf_l",
  "thumb_01_l",
  "thumb_02_l",
  "thumb_03_l",
  "thumb_04_leaf_l",
  "clavicle_r",
  "upperarm_r",
  "lowerarm_r",
  "hand_r",
  "index_01_r",
  "index_02_r",
  "index_03_r",
  "index_04_leaf_r",
  "middle_01_r",
  "middle_02_r",
  "middle_03_r",
  "middle_04_leaf_r",
  "pinky_01_r",
  "pinky_02_r",
  "pinky_03_r",
  "pinky_04_leaf_r",
  "ring_01_r",
  "ring_02_r",
  "ring_03_r",
  "ring_04_leaf_r",
  "thumb_01_r",
  "thumb_02_r",
  "thumb_03_r",
  "thumb_04_leaf_r",
  "thigh_l",
  "calf_l",
  "foot_l",
  "ball_l",
  "ball_leaf_l",
  "thigh_r",
  "calf_r",
  "foot_r",
  "ball_r",
  "ball_leaf_r",
] as const;

export type AvatarBoneName = typeof AVATAR_BONE_NAMES[number];

export const AVATAR_BONE_PARENT: Record<AvatarBoneName, AvatarBoneName | null> = {
  "root": null,
  "pelvis": "root",
  "spine_01": "pelvis",
  "spine_02": "spine_01",
  "spine_03": "spine_02",
  "neck_01": "spine_03",
  "head": "neck_01",
  "head_leaf": "head",
  "clavicle_l": "spine_03",
  "upperarm_l": "clavicle_l",
  "lowerarm_l": "upperarm_l",
  "hand_l": "lowerarm_l",
  "index_01_l": "hand_l",
  "index_02_l": "index_01_l",
  "index_03_l": "index_02_l",
  "index_04_leaf_l": "index_03_l",
  "middle_01_l": "hand_l",
  "middle_02_l": "middle_01_l",
  "middle_03_l": "middle_02_l",
  "middle_04_leaf_l": "middle_03_l",
  "pinky_01_l": "hand_l",
  "pinky_02_l": "pinky_01_l",
  "pinky_03_l": "pinky_02_l",
  "pinky_04_leaf_l": "pinky_03_l",
  "ring_01_l": "hand_l",
  "ring_02_l": "ring_01_l",
  "ring_03_l": "ring_02_l",
  "ring_04_leaf_l": "ring_03_l",
  "thumb_01_l": "hand_l",
  "thumb_02_l": "thumb_01_l",
  "thumb_03_l": "thumb_02_l",
  "thumb_04_leaf_l": "thumb_03_l",
  "clavicle_r": "spine_03",
  "upperarm_r": "clavicle_r",
  "lowerarm_r": "upperarm_r",
  "hand_r": "lowerarm_r",
  "index_01_r": "hand_r",
  "index_02_r": "index_01_r",
  "index_03_r": "index_02_r",
  "index_04_leaf_r": "index_03_r",
  "middle_01_r": "hand_r",
  "middle_02_r": "middle_01_r",
  "middle_03_r": "middle_02_r",
  "middle_04_leaf_r": "middle_03_r",
  "pinky_01_r": "hand_r",
  "pinky_02_r": "pinky_01_r",
  "pinky_03_r": "pinky_02_r",
  "pinky_04_leaf_r": "pinky_03_r",
  "ring_01_r": "hand_r",
  "ring_02_r": "ring_01_r",
  "ring_03_r": "ring_02_r",
  "ring_04_leaf_r": "ring_03_r",
  "thumb_01_r": "hand_r",
  "thumb_02_r": "thumb_01_r",
  "thumb_03_r": "thumb_02_r",
  "thumb_04_leaf_r": "thumb_03_r",
  "thigh_l": "pelvis",
  "calf_l": "thigh_l",
  "foot_l": "calf_l",
  "ball_l": "foot_l",
  "ball_leaf_l": "ball_l",
  "thigh_r": "pelvis",
  "calf_r": "thigh_r",
  "foot_r": "calf_r",
  "ball_r": "foot_r",
  "ball_leaf_r": "ball_r",
} as const;

export const AVATAR_BONE_CHILDREN: Record<AvatarBoneName, readonly AvatarBoneName[]> = {
  "root": ["pelvis"],
  "pelvis": ["spine_01", "thigh_l", "thigh_r"],
  "spine_01": ["spine_02"],
  "spine_02": ["spine_03"],
  "spine_03": ["neck_01", "clavicle_l", "clavicle_r"],
  "neck_01": ["head"],
  "head": ["head_leaf"],
  "head_leaf": [],
  "clavicle_l": ["upperarm_l"],
  "upperarm_l": ["lowerarm_l"],
  "lowerarm_l": ["hand_l"],
  "hand_l": ["index_01_l", "middle_01_l", "pinky_01_l", "ring_01_l", "thumb_01_l"],
  "index_01_l": ["index_02_l"],
  "index_02_l": ["index_03_l"],
  "index_03_l": ["index_04_leaf_l"],
  "index_04_leaf_l": [],
  "middle_01_l": ["middle_02_l"],
  "middle_02_l": ["middle_03_l"],
  "middle_03_l": ["middle_04_leaf_l"],
  "middle_04_leaf_l": [],
  "pinky_01_l": ["pinky_02_l"],
  "pinky_02_l": ["pinky_03_l"],
  "pinky_03_l": ["pinky_04_leaf_l"],
  "pinky_04_leaf_l": [],
  "ring_01_l": ["ring_02_l"],
  "ring_02_l": ["ring_03_l"],
  "ring_03_l": ["ring_04_leaf_l"],
  "ring_04_leaf_l": [],
  "thumb_01_l": ["thumb_02_l"],
  "thumb_02_l": ["thumb_03_l"],
  "thumb_03_l": ["thumb_04_leaf_l"],
  "thumb_04_leaf_l": [],
  "clavicle_r": ["upperarm_r"],
  "upperarm_r": ["lowerarm_r"],
  "lowerarm_r": ["hand_r"],
  "hand_r": ["index_01_r", "middle_01_r", "pinky_01_r", "ring_01_r", "thumb_01_r"],
  "index_01_r": ["index_02_r"],
  "index_02_r": ["index_03_r"],
  "index_03_r": ["index_04_leaf_r"],
  "index_04_leaf_r": [],
  "middle_01_r": ["middle_02_r"],
  "middle_02_r": ["middle_03_r"],
  "middle_03_r": ["middle_04_leaf_r"],
  "middle_04_leaf_r": [],
  "pinky_01_r": ["pinky_02_r"],
  "pinky_02_r": ["pinky_03_r"],
  "pinky_03_r": ["pinky_04_leaf_r"],
  "pinky_04_leaf_r": [],
  "ring_01_r": ["ring_02_r"],
  "ring_02_r": ["ring_03_r"],
  "ring_03_r": ["ring_04_leaf_r"],
  "ring_04_leaf_r": [],
  "thumb_01_r": ["thumb_02_r"],
  "thumb_02_r": ["thumb_03_r"],
  "thumb_03_r": ["thumb_04_leaf_r"],
  "thumb_04_leaf_r": [],
  "thigh_l": ["calf_l"],
  "calf_l": ["foot_l"],
  "foot_l": ["ball_l"],
  "ball_l": ["ball_leaf_l"],
  "ball_leaf_l": [],
  "thigh_r": ["calf_r"],
  "calf_r": ["foot_r"],
  "foot_r": ["ball_r"],
  "ball_r": ["ball_leaf_r"],
  "ball_leaf_r": [],
} as const;

export const AVATAR_BONE_ALIAS: Record<AvatarBoneName, string> = {
  "root": "root / scene-scale orientation bone",
  "pelvis": "hips / pelvis driver",
  "spine_01": "lower spine",
  "spine_02": "mid spine",
  "spine_03": "upper spine / chest",
  "neck_01": "neck",
  "head": "head",
  "head_leaf": "head end / head tip",
  "clavicle_l": "left clavicle / shoulder",
  "upperarm_l": "left upper arm",
  "lowerarm_l": "left forearm",
  "hand_l": "left wrist / hand",
  "index_01_l": "left index finger proximal / base",
  "index_02_l": "left index finger intermediate / middle",
  "index_03_l": "left index finger distal",
  "index_04_leaf_l": "left index finger tip end",
  "middle_01_l": "left middle finger proximal / base",
  "middle_02_l": "left middle finger intermediate / middle",
  "middle_03_l": "left middle finger distal",
  "middle_04_leaf_l": "left middle finger tip end",
  "pinky_01_l": "left pinky finger proximal / base",
  "pinky_02_l": "left pinky finger intermediate / middle",
  "pinky_03_l": "left pinky finger distal",
  "pinky_04_leaf_l": "left pinky finger tip end",
  "ring_01_l": "left ring finger proximal / base",
  "ring_02_l": "left ring finger intermediate / middle",
  "ring_03_l": "left ring finger distal",
  "ring_04_leaf_l": "left ring finger tip end",
  "thumb_01_l": "left thumb base / CMC-metacarpal",
  "thumb_02_l": "left thumb proximal",
  "thumb_03_l": "left thumb distal",
  "thumb_04_leaf_l": "left thumb tip end",
  "clavicle_r": "right clavicle / shoulder",
  "upperarm_r": "right upper arm",
  "lowerarm_r": "right forearm",
  "hand_r": "right wrist / hand",
  "index_01_r": "right index finger proximal / base",
  "index_02_r": "right index finger intermediate / middle",
  "index_03_r": "right index finger distal",
  "index_04_leaf_r": "right index finger tip end",
  "middle_01_r": "right middle finger proximal / base",
  "middle_02_r": "right middle finger intermediate / middle",
  "middle_03_r": "right middle finger distal",
  "middle_04_leaf_r": "right middle finger tip end",
  "pinky_01_r": "right pinky finger proximal / base",
  "pinky_02_r": "right pinky finger intermediate / middle",
  "pinky_03_r": "right pinky finger distal",
  "pinky_04_leaf_r": "right pinky finger tip end",
  "ring_01_r": "right ring finger proximal / base",
  "ring_02_r": "right ring finger intermediate / middle",
  "ring_03_r": "right ring finger distal",
  "ring_04_leaf_r": "right ring finger tip end",
  "thumb_01_r": "right thumb base / CMC-metacarpal",
  "thumb_02_r": "right thumb proximal",
  "thumb_03_r": "right thumb distal",
  "thumb_04_leaf_r": "right thumb tip end",
  "thigh_l": "left thigh / upper leg",
  "calf_l": "left calf / lower leg",
  "foot_l": "left foot",
  "ball_l": "left ball / toe base",
  "ball_leaf_l": "left toe end",
  "thigh_r": "right thigh / upper leg",
  "calf_r": "right calf / lower leg",
  "foot_r": "right foot",
  "ball_r": "right ball / toe base",
  "ball_leaf_r": "right toe end",
} as const;

export const AVATAR_WEIGHTED_JOINTS = [
  "spine_01",
  "spine_02",
  "spine_03",
  "neck_01",
  "head",
  "head_leaf",
  "clavicle_l",
  "upperarm_l",
  "lowerarm_l",
  "hand_l",
  "index_01_l",
  "index_02_l",
  "index_03_l",
  "index_04_leaf_l",
  "middle_01_l",
  "middle_02_l",
  "middle_03_l",
  "middle_04_leaf_l",
  "pinky_01_l",
  "pinky_02_l",
  "pinky_03_l",
  "pinky_04_leaf_l",
  "ring_01_l",
  "ring_02_l",
  "ring_03_l",
  "ring_04_leaf_l",
  "thumb_01_l",
  "thumb_02_l",
  "thumb_03_l",
  "clavicle_r",
  "upperarm_r",
  "lowerarm_r",
  "hand_r",
  "index_01_r",
  "index_02_r",
  "index_03_r",
  "index_04_leaf_r",
  "middle_01_r",
  "middle_02_r",
  "middle_03_r",
  "middle_04_leaf_r",
  "pinky_01_r",
  "pinky_02_r",
  "pinky_03_r",
  "pinky_04_leaf_r",
  "ring_01_r",
  "ring_02_r",
  "ring_03_r",
  "ring_04_leaf_r",
  "thumb_01_r",
  "thumb_02_r",
  "thumb_03_r",
  "thigh_l",
  "calf_l",
  "foot_l",
  "ball_l",
  "ball_leaf_l",
  "thigh_r",
  "calf_r",
  "foot_r",
  "ball_r",
  "ball_leaf_r",
] as const satisfies readonly AvatarBoneName[];

export const AVATAR_NON_WEIGHTED_DRIVERS = [
  "root",
  "pelvis",
  "thumb_04_leaf_l",
  "thumb_04_leaf_r",
] as const satisfies readonly AvatarBoneName[];

export const AVATAR_FINGER_CHAINS = {
  "left": {
    "thumb": [
      "thumb_01_l",
      "thumb_02_l",
      "thumb_03_l",
      "thumb_04_leaf_l"
    ],
    "index": [
      "index_01_l",
      "index_02_l",
      "index_03_l",
      "index_04_leaf_l"
    ],
    "middle": [
      "middle_01_l",
      "middle_02_l",
      "middle_03_l",
      "middle_04_leaf_l"
    ],
    "ring": [
      "ring_01_l",
      "ring_02_l",
      "ring_03_l",
      "ring_04_leaf_l"
    ],
    "pinky": [
      "pinky_01_l",
      "pinky_02_l",
      "pinky_03_l",
      "pinky_04_leaf_l"
    ]
  },
  "right": {
    "thumb": [
      "thumb_01_r",
      "thumb_02_r",
      "thumb_03_r",
      "thumb_04_leaf_r"
    ],
    "index": [
      "index_01_r",
      "index_02_r",
      "index_03_r",
      "index_04_leaf_r"
    ],
    "middle": [
      "middle_01_r",
      "middle_02_r",
      "middle_03_r",
      "middle_04_leaf_r"
    ],
    "ring": [
      "ring_01_r",
      "ring_02_r",
      "ring_03_r",
      "ring_04_leaf_r"
    ],
    "pinky": [
      "pinky_01_r",
      "pinky_02_r",
      "pinky_03_r",
      "pinky_04_leaf_r"
    ]
  }
} as const satisfies Record<"left" | "right", Record<"thumb" | "index" | "middle" | "ring" | "pinky", readonly AvatarBoneName[]>>;

export const AVATAR_BONE_GROUPS = {
  "all": [
    "root",
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03",
    "neck_01",
    "head",
    "head_leaf",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "ball_leaf_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "ball_leaf_r"
  ],
  "weightedJoints": [
    "spine_01",
    "spine_02",
    "spine_03",
    "neck_01",
    "head",
    "head_leaf",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "ball_leaf_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "ball_leaf_r"
  ],
  "nonWeightedDrivers": [
    "root",
    "pelvis",
    "thumb_04_leaf_l",
    "thumb_04_leaf_r"
  ],
  "centerline": [
    "root",
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03",
    "neck_01",
    "head",
    "head_leaf"
  ],
  "rootMotion": [
    "root",
    "pelvis"
  ],
  "hips": [
    "pelvis"
  ],
  "spine": [
    "spine_01",
    "spine_02",
    "spine_03"
  ],
  "torso": [
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03"
  ],
  "neckHead": [
    "neck_01",
    "head",
    "head_leaf"
  ],
  "lookAt": [
    "neck_01",
    "head"
  ],
  "upperBody": [
    "spine_02",
    "spine_03",
    "neck_01",
    "head",
    "head_leaf",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ],
  "upperBodyNoFingers": [
    "spine_02",
    "spine_03",
    "neck_01",
    "head",
    "head_leaf",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r"
  ],
  "lowerBody": [
    "pelvis",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "ball_leaf_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "ball_leaf_r"
  ],
  "leftArm": [
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l"
  ],
  "rightArm": [
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r"
  ],
  "arms": [
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r"
  ],
  "leftLeg": [
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "ball_leaf_l"
  ],
  "rightLeg": [
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "ball_leaf_r"
  ],
  "legs": [
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "ball_leaf_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "ball_leaf_r"
  ],
  "leftHand": [
    "hand_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l"
  ],
  "rightHand": [
    "hand_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ],
  "hands": [
    "hand_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l",
    "hand_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ],
  "leftFingers": [
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l"
  ],
  "rightFingers": [
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ],
  "fingers": [
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ],
  "leftFingerDrivers": [
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l"
  ],
  "rightFingerDrivers": [
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r"
  ],
  "fingerDrivers": [
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r"
  ],
  "fingerTips": [
    "thumb_04_leaf_l",
    "index_04_leaf_l",
    "middle_04_leaf_l",
    "ring_04_leaf_l",
    "pinky_04_leaf_l",
    "thumb_04_leaf_r",
    "index_04_leaf_r",
    "middle_04_leaf_r",
    "ring_04_leaf_r",
    "pinky_04_leaf_r"
  ],
  "fingerBases": [
    "thumb_01_l",
    "index_01_l",
    "middle_01_l",
    "ring_01_l",
    "pinky_01_l",
    "thumb_01_r",
    "index_01_r",
    "middle_01_r",
    "ring_01_r",
    "pinky_01_r"
  ],
  "fingerMiddles": [
    "thumb_02_l",
    "index_02_l",
    "middle_02_l",
    "ring_02_l",
    "pinky_02_l",
    "thumb_02_r",
    "index_02_r",
    "middle_02_r",
    "ring_02_r",
    "pinky_02_r"
  ],
  "fingerDistals": [
    "thumb_03_l",
    "index_03_l",
    "middle_03_l",
    "ring_03_l",
    "pinky_03_l",
    "thumb_03_r",
    "index_03_r",
    "middle_03_r",
    "ring_03_r",
    "pinky_03_r"
  ],
  "leftInteractionArm": [
    "spine_03",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l"
  ],
  "rightInteractionArm": [
    "spine_03",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ],
  "twoHandInteraction": [
    "spine_02",
    "spine_03",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ],
  "locomotionCore": [
    "root",
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "ball_leaf_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "ball_leaf_r"
  ],
  "locomotionNoUpperBody": [
    "root",
    "pelvis",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "ball_leaf_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "ball_leaf_r"
  ],
  "headAndHands": [
    "neck_01",
    "head",
    "head_leaf",
    "hand_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "thumb_04_leaf_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "index_04_leaf_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "middle_04_leaf_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "ring_04_leaf_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "pinky_04_leaf_l",
    "hand_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "thumb_04_leaf_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "index_04_leaf_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "middle_04_leaf_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "ring_04_leaf_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "pinky_04_leaf_r"
  ]
} as const satisfies Record<string, readonly AvatarBoneName[]>;

export type AvatarBoneGroupName = keyof typeof AVATAR_BONE_GROUPS;

export function getAvatarBoneGroup(group: AvatarBoneGroupName): readonly AvatarBoneName[] {
  return AVATAR_BONE_GROUPS[group];
}

export function isAvatarBoneName(value: string): value is AvatarBoneName {
  return (AVATAR_BONE_NAMES as readonly string[]).includes(value);
}

export function sideOfBone(bone: AvatarBoneName): "left" | "right" | "center" {
  if (bone.endsWith("_l")) return "left";
  if (bone.endsWith("_r")) return "right";
  return "center";
}

export function mirrorBoneName(bone: AvatarBoneName): AvatarBoneName | null {
  const mirrored = bone.endsWith("_l")
    ? bone.replace(/_l$/, "_r")
    : bone.endsWith("_r")
      ? bone.replace(/_r$/, "_l")
      : null;
  return mirrored && isAvatarBoneName(mirrored) ? mirrored : null;
}
